name: C/C++ CI

on:
  push:
    branches: [ "macos", "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4


    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: "6.10.2"
        arch: "win64_mingw"
        tools: 'tools_mingw1310'

    - name: Path stuff
      shell: bash
      run: echo "${{ github.workspace }}\Qt\Tools\mingw1310_64\bin" >> $GITHUB_PATH

    - name: qmake
      working-directory: ${{github.workspace}}
      run: qmake -makefile
      
    - name: make
      working-directory: ${{github.workspace}}

      run: make -j4
    - name: deploy
      working-directory: ${{github.workspace}}/build/Release
      run: windeployqt.exe ./

    - name: upload
      uses: actions/upload-artifact@v6.0.0
      
      with:
        path: ${{github.workspace}}/build
        name: "windows-x86_64"

  build-mac-old:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '5.*.*'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'         
        
    - name: qmake
   
      working-directory: ${{github.workspace}}
      run: qmake -makefile 
      
    - name: make
      working-directory: ${{github.workspace}}

      run: make -j4
    - name: deploy
      working-directory: ${{github.workspace}}/build/Release
      run: macdeployqt wappysav.app

    - name: upload
      uses: actions/upload-artifact@v6.0.0
      
      with:
        path: ${{github.workspace}}/build
        name: "macos-x86_64-qt5"

  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.10.2'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'         
        
    - name: qmake
   
      working-directory: ${{github.workspace}}
      run: qmake -makefile QMAKE_APPLE_DEVICE_ARCHS="x86_64 arm64"
      
    - name: make
      working-directory: ${{github.workspace}}

      run: make -j4
    - name: deploy
      working-directory: ${{github.workspace}}/build/Release
      run: macdeployqt wappysav.app

    - name: upload
      uses: actions/upload-artifact@v6.0.0
      
      with:
        path: ${{github.workspace}}/build
        name: "macos-universal-qt6"
  build-linux:

    runs-on: ubuntu-22.04
    env:
      QT_VERSION: 6.10.2
      BUILD_DIR: build

    steps:
    - uses: actions/checkout@v4

    

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.10.2'
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'        
        
    - name: qmake
   
      working-directory: ${{github.workspace}}
      run: qmake -makefile
      
    - name: make
      working-directory: ${{github.workspace}}

      run: |
        make -j4
        sudo make install
        ls -R
     
    - name: AppImageTool deployment
      run: |
        sudo add-apt-repository universe
        sudo apt install libfuse2
        wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
        chmod +x appimage-builder-x86_64.AppImage
        sudo mv appimage-builder-x86_64.AppImage /usr/local/bin/appimage-builder
        cp -a /home/runner/work/wappysav/Qt/6.10.2/gcc_64/lib/ ${{github.workspace}}/AppDir/usr/lib
        cd ${{github.workspace}} && appimage-builder --recipe AppImageBuilder.yml
     
  


   
    - name: upload
      uses: actions/upload-artifact@v6.0.0
      
      with:
        path: ${{github.workspace}}/AppDir/
        name: "linux-x86_64"
      
      

      

      

      
